"""add exercise_timers

Revision ID: 6f5c50ce838d
Revises: 7f16e3eb4aa0
Create Date: 2026-08-03 17:29:51.524441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5c50ce838d'
down_revision = '7f16e3eb4aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_timers',
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('exercise')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_timers')
    # ### end Alembic commands ###
