"""initial schema

Revision ID: 7f16e3eb4aa0
Revises: 
Create Date: 2026-08-03 15:28:41.207519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f16e3eb4aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part', 'exercise', name='uq_part_exercise')
    )
    with op.batch_alter_table('custom_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_exercises_part'), ['part'], unique=False)

    op.create_table('day_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'part', 'exercise', name='uq_day_part_exercise')
    )
    with op.batch_alter_table('day_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_exercises_day'), ['day'], unique=False)

    op.create_table('exercise_notes',
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('exercise')
    )
    op.create_table('training_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('set_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sets_exercise'), ['exercise'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sets_exercise'))

    op.drop_table('training_sets')
    op.drop_table('exercise_notes')
    with op.batch_alter_table('day_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_exercises_day'))

    op.drop_table('day_exercises')
    with op.batch_alter_table('custom_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_exercises_part'))

    op.drop_table('custom_exercises')
    # ### end Alembic commands ###
